version: '3.1'
networks: 
  mynetwork:
    driver: bridge
services:
  react-frontend:
    container_name: post
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      - mynetwork
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development


      
    


    
    
      


